apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: "{{REPLICAS}}"
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: "{{APP_IMAGE_NAME}}:{{APP_IMAGE_TAG}}"
          resources: "{{APP_RESOURCES}}"
          ports:
            - containerPort: "{{APP_PORT}}"
